[package]
name = "rokujuuyon"
version = "0.1.0"
authors = ["ninjawarrior1337 <me@treelar.xyz>"]
edition = "2021"

[features]
default = ["imagequant", "exoquant"]
threads = ["indicatif/rayon"]

[dependencies]
image = {workspace = true}
imagequant = { version = "4.2.0", default-features = false,  optional = true }
exoquant = { version = "0.2.0", optional = true}

base64 = "0.21.2"
crc32fast = "1.3.2"
bytes = "1.4.0"
rayon = "1.7.0"
indicatif = { version = "0.17.3", features = ["rayon"] }
crossbeam-channel = "0.5.8"
num_cpus = "1.15.0"
clap = { version = "4.3.0", features = ["derive"] }
anyhow = "1.0.71"
bitvec = "1.0.1"
